import type { Metadata } from "next";
import { Geist, Geist_Mono, Xanh_Mono, Space_Mono } from "next/font/google";
import "./globals.css";
import { ScrollSmootherInit } from "@/components/ScrollSmootherInit";
import LiquidEther from "@/components/LiquidEther";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const xanhMono = Xanh_Mono({
  variable: "--font-xanh-mono",
  subsets: ["latin"],
  weight: ["400"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white ${geistSans.variable} ${geistMono.variable} ${xanhMono.variable} ${spaceMono.variable} antialiased`}
      >
         
         <div className="fixed invert  w-screen h-screen inset-0 z-0">
        <LiquidEther 
          colors={['#000000',  '#006AF9', '#0000FF',]}
          mouseForce={10}
          cursorSize={100}
          autoDemo={false}
          autoSpeed={0.15}
          autoIntensity={2.2}
          resolution={0.4}
        />
      </div>
        <div id="smooth-wrapper">
          <div id="smooth-content">
            {children}
          </div>
        </div>
        <ScrollSmootherInit />
      </body>
    </html>
  );
}
